baseURL = "https://gauthierwallet.com"
languageCode = "en-us"
title = "Gauthier Wallet"
copyright = "© {year}"
googleAnalytics = "UA-180662831-1"

[params]
  title = "Gauthier Wallet"
  name = "Gauthier Wallet"
  website = "https://gauthierwallet.com/"
  description = "Software Engineer, Explorer of Life."
  twitter = "https://twitter.com/Ninnir"
  github = "https://github.com/Ninir"
  linkedin = "https://www.linkedin.com/in/gauthier-wallet-8b084260/"
  instagram = "https://www.instagram.com/gauthier.wallet/"
  iconOrder = ["Twitter", "GitHub", "LinkedIn", "Instagram"]
  showPageTitleInTOC = true

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Homepage"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "thoughts"
    name = "Thoughts"
    url = "/thoughts/"
    weight = 10