baseURL = "https://gauthierwallet.com"
languageCode = "en-us"
title = "Gauthier Wallet - Tech Leader & Continuous Learner"
copyright = "© {year}"
googleAnalytics = "UA-180662831-1"

[params]
title = "Gauthier Wallet - Tech Leader"
name = "Gauthier Wallet"
website = "https://gauthierwallet.com/"
description = "Software Engineer at heart looking to expand his knowledge and discover new worlds."
github = "https://github.com/Ninir"
linkedin = "https://www.linkedin.com/in/gauthier-wallet-8b084260/"
iconOrder = ["GitHub", "LinkedIn"]
showPageTitleInTOC = true

[menu]
[[menu.main]]
identifier = "home"
name = "Homepage"
url = "/"
weight = 1
